### PR TITLE
Use ICommand

### PR DESCRIPTION
**Pull request by timunie**
I use RelayCommand from MVVM Toolkit because I like this the most.

### CODE REVIEW

**Comment by sn4k3** [comment]
I found the [problem](https://github.com/sn4k3/UVtools/commit/aed8136baefdf2f1864c9e1d0c3d16dadf396169) and reported on the [issue](https://github.com/AvaloniaUI/Avalonia/issues/8835#issuecomment-1229460805).

But since `ICommand` adds more code, new dependency and i'm not following MVVM approach i prefer to keep with the basic `Binding` approach.
Thank you for look into this, i appreciate your time and effort 👍

**Comment by timunie** [comment]
While ICommand adds a bit more code, it's faster and more reliable. Also you can enable and disable it, but you don't need to. 

The best is, that you can use CompiledBindings which use no reflection.

**Comment by sn4k3** [comment]
> The best is, that you can use CompiledBindings which use no reflection.

Is that by default or requires other code?

**Comment by timunie** [comment]
> > The best is, that you can use CompiledBindings which use no reflection.
> 
> Is that by default or requires other code?

See: https://docs.avaloniaui.net/docs/data-binding/compiledbindings?q=compiled

Also the MVVM Toolkit I used has SourceGenerators. So you can do: 

```
[RelayCommand]
private void Undo()
{ 
   ...
}
```
This makes the additional needed code almost nothing. See: https://docs.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/overview

Happx coding
Tim

**Comment by sn4k3** [comment]
Thank you, so far i only have used direct bindings, I will read your docs. It can be a pain to convert all app to use `ICommand` but if it worth I may do it after all.
Regards

**Pull request closed without merging**
