### PR TITLE
Remove dupe Arch dependency from README

### PR DESCRIPTION
**Pull request by muesli**
libdc1394 was listed twice.

### CODE REVIEW

**Comment by sn4k3** [comment]
Thanks 👍

**Comment by muesli** [comment]
Just a heads up, I've also added a simple `uvtools-bin` package to the AUR: https://aur.archlinux.org/packages/uvtools-bin

This make installation on Arch as easy as running `yay -S uvtools-bin`

**Comment by sn4k3** [comment]
Is that auto-maintainable?
Also does UVtools_linux-x64_3.5.6.AppImage works with arch? 

Can you also have a look at: https://github.com/sn4k3/UVtools/discussions/525 ?

**Comment by muesli** [comment]
> Is that auto-maintainable?

Not fully. You'll get out-of-date notifications, but the maintainer is supposed to bump the version and test the resulting package manually. I'll try my best :smile: 
 
> Also does UVtools_linux-x64_3.5.6.AppImage works with arch?
> Can you also have a look at: #525 ?

Can not reproduce that here, the AppImage works fine for me (once I symlink `libdl.so`). I'll quickly comment on this ticket.

**Pull request merged**
